version: '2'
services:
    bbs:
      build:
        context: .
        dockerfile: Dockerfile
      container_name: backend
      ports:
        - "8071:8071"
      depends_on:
      - postgres
      environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=123
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

    postgres:
      image: postgres:13.4
      container_name: postgres
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=123
      command: postgres
      volumes: 
        - ./src/main/resources/schema.sql:/docker-entrypoint-initdb.d/create_tables.sql
        
      
        