version: '3.3'
services:
    web:
      build:
        context: .
        dockerfile: Dockerfile
      container_name: backend
      ports:
        - "8080:8080"
      depends_on:
      - mysql
      environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/mydb
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=1234
      - SPRING_JPA_HIBERNATE_DDL_AUTO=none
      - PORT=8080

    mysql:
      image: mysql:8.0
      restart: always
      container_name: mysql
      environment:
        MYSQL_DATABASE: 'mydb'
        # So you don't have to use root, but you can if you like
        MYSQL_USER: 'user'
        MYSQL_PASSWORD: '1234'
        MYSQL_ROOT_PASSWORD: '1234'
      ports:
        - '8088:3306'
      expose:
        # Opens port 3306 on the container
        - '3306'
        # Where our data will be persisted
      volumes:
        - my-db:/var/lib/mysql
        - ./src/main/resources/schema.sql:/docker-entrypoint-initdb.d/create_tables.sql
# Names our volume
volumes:
  my-db: