server:
  port: 8079
spring:
   application:
    name: 'lab-eng-software'

   datasource: 
    url: jdbc:mysql://localhost:3306/mydb
    username: root
    password: 1234
    driver-class-name: com.mysql.jdbc.Driver


spring.jpa:
  hibernate:
    ddl-auto: none
